export { default as Home } from './Home'
export { default as About } from './About'
export { default as Work } from './Work'
export { default as Blog } from './Blog'
export { default as Page404 } from './404'
