export { default as Home } from 'pages/Home'
export { default as About } from 'pages/About'
export { default as Work } from 'pages/Work'
export { default as Blog } from 'pages/Blog'
export { default as BlogDetail } from 'pages/Blog/Detail'
export { default as Page404 } from 'pages/404'
